#!/bin/sh

export CHECKMARK="✔"
export CROSSMARK="✘"
export TABCHAR="╰┈➤ "
export INFOCHAR=" ~ "


export MAKEFLAGS="-j$(grep "processor" /proc/cpuinfo | wc -l)"

export XIB_DIR="/var/lib/xib"
export XIB_BUILDFILES="$XIB_DIR/buildfiles"
export XIB_CHROOT="$XIB_DIR/chroot"
export XIB_EXPORT="$XIB_DIR/export"

export PRIV_KEY="/home/david/.ssh/xi.pem"
export PUB_KEY="/home/david/.ssh/xi.pub"
export DEVELOPMENT_BUILDFILES="/home/david/docs/proj/xilinux/buildfiles"

export BUILDFILES_GIT_REPO="https://xi.davidovski.xyz/git/buildfiles.git"
export INSTALLED_PACKAGES="$XIB_CHROOT/installed"

mkdir -p $XIB_DIR $XIB_BUILDFILES $XIB_CHROOT $XIB_EXPORT

if [ -d $DEVELOPMENT_BUILDFILES ]; then
    cp -r $DEVELOPMENT_BUILDFILES/* $XIB_BUILDFILES/
else
    if [ -d $XIB_BUILDFILES/.git ]; then
        cd $XIB_BUILDFILES
        git pull
        cd $OLDPWD
    else
        git clone $BUILDFILES_GIT_REPO $XIB_BUILDFILES
    fi
fi

[ -f $INSTALLED_PACKAGES ] || touch $INSTALLED_PACKAGES

[ -f $XIB_CHROOT/etc/resolv.conf ] || cp /etc/resolv.conf $XIB_CHROOT/etc/resolv.conf
